name: Tayyor APK Qurish

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni yuklash
        uses: actions/checkout@v4

      - name: Buildozer spec faylini yaratish
        run: |
          pip install buildozer
          buildozer init
          sed -i 's/title = My Application/title = Aqlli TalkBack/g' buildozer.spec
          sed -i 's/package.name = myapp/package.name = aqllitalkback/g' buildozer.spec
          sed -i 's/requirements = python3,kivy/requirements = python3,kivy,tensorflow-lite/g' buildozer.spec

      - name: Tayyor tizimda APK yig'ish
        uses: ArtemGovorov/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: stable

      - name: APKni saqlash
        uses: actions/upload-artifact@v4
        with:
          name: Aqlli_TalkBack_Ilova
          path: bin/*.apk
