name: Oflayn Modelni Tayyorlash

on:
  push:
    branches:
      - main
      - master

jobs:
  build_model:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni yuklash
        uses: actions/checkout@v4

      - name: Pythonni sozlash
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Modelni yuklab olish va yengillashtirish
        run: |
          pip install ultralytics
          python -c "from ultralytics import YOLO; model = YOLO('yolov8n.pt'); model.export(format='tflite')"

      - name: Tayyor modelni saqlash
        uses: actions/upload-artifact@v4
        with:
          name: oflayn-model
          path: yolov8n_saved_model/yolov8n_float32.tflite
