name: Tayyor APK Qurish

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni yuklash
        uses: actions/checkout@v4

      - name: APK faylini yig'ish (Buildozer Action)
        uses: jensens/buildozer-action@v2
        with:
          buildozer_version: stable
          command: android debug

      - name: APKni saqlash
        uses: actions/upload-artifact@v4
        with:
          name: Aqlli_TalkBack_Ilova
          path: bin/*.apk
